t

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -59,33 +59,33 @@ jobs:
         echo "Databricks version"
         databricks -v
 
-        DLT_START=$SECONDS
-        DLT_START_ISO=$(date --iso-8601=seconds)
-        JOB_ID=$(databricks jobs run-now ${{ env.TEST_DLT_PIPELINE_ID }} --no-wait | jq .run_id)
-        sleep 15
-        while true; do
-          DLT_STATUS=$(databricks jobs get-run $(JOB_ID) |jq .state.life_cycle_state)
-          if [ "$DLT_STATUS" = "CANCELED" -o "$DLT_STATUS" = "SKIPPED" -o "$DLT_STATUS" = "FAILED" -o "$DLT_STATUS" = "SUCCESS" ]; then
-            echo "Exiting loop with status '$DLT_STATUS'"
-            break
-          fi
-          echo "DLT pipeline status is '$DLT_STATUS'. Waiting..."
-          sleep 15
-        done
-        DLT_FINISH=$SECONDS
-        DLT_ERRORS=$(( "$DLT_STATUS" = "FAILED" ? 1 : 0 ))
-        DLT_SKIPPED=$(( "$DLT_STATUS" = "CANCELED" ? 1 : 0 ))
-        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites><testsuite name=\"DLT Integration test\" tests=\"1\" skipped=\"$DLT_SKIPPED\" errors=\"$DLT_ERRORS\" failures=\"$DLT_ERRORS\" time=\"$((DLT_FINISH-DLT_START))\" timestamp=\"${DLT_START_ISO}\">" > test-dlt.xml
-        echo "<testcase classname=\"DLTIntegration\" name=\"${{ env.TEST_DLT_PIPELINE_NAME }}\" time=\"$((DLT_FINISH-DLT_START))\">" >> test-dlt.xml
-        if [ "$DLT_STATUS" = "FAILED" ]; then
-          echo "<failure message=\"DLT test failure\">Pipeline update with ID ${JOB_ID} has failed</failure>" >> test-dlt.xml
-        elif [ "$DLT_STATUS" = "SKIPPED" ]; then
-          echo '<skipped />' >> test-dlt.xml
-        fi
-        echo '</testcase></testsuite></testsuites>' >> test-dlt.xml
-        if [ "$DLT_STATUS" != "SUCCESS" ]; then
-          exit 1
-        fi         
+        #DLT_START=$SECONDS
+        #DLT_START_ISO=$(date --iso-8601=seconds)
+        #JOB_ID=$(databricks jobs run-now ${{ env.TEST_DLT_PIPELINE_ID }} --no-wait | jq .run_id)
+        #sleep 15
+        #while true; do
+        #  DLT_STATUS=$(databricks jobs get-run $(JOB_ID) |jq .state.life_cycle_state)
+        #  if [ "$DLT_STATUS" = "CANCELED" -o "$DLT_STATUS" = "SKIPPED" -o "$DLT_STATUS" = "FAILED" -o "$DLT_STATUS" = "SUCCESS" ]; then
+        #    echo "Exiting loop with status '$DLT_STATUS'"
+        #    break
+        #  fi
+        #  echo "DLT pipeline status is '$DLT_STATUS'. Waiting..."
+        #  sleep 15
+        #done
+        #DLT_FINISH=$SECONDS
+        #DLT_ERRORS=$(( "$DLT_STATUS" = "FAILED" ? 1 : 0 ))
+        #DLT_SKIPPED=$(( "$DLT_STATUS" = "CANCELED" ? 1 : 0 ))
+        #echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites><testsuite name=\"DLT Integration test\" tests=\"1\" skipped=\"$DLT_SKIPPED\" errors=\"$DLT_ERRORS\" #failures=\"$DLT_ERRORS\" time=\"$((DLT_FINISH-DLT_START))\" timestamp=\"${DLT_START_ISO}\">" > test-dlt.xml
+        #echo "<testcase classname=\"DLTIntegration\" name=\"${{ env.TEST_DLT_PIPELINE_NAME }}\" time=\"$((DLT_FINISH-DLT_START))\">" >> test-dlt.xml
+        #if [ "$DLT_STATUS" = "FAILED" ]; then
+        #  echo "<failure message=\"DLT test failure\">Pipeline update with ID ${JOB_ID} has failed</failure>" >> test-dlt.xml
+        #elif [ "$DLT_STATUS" = "SKIPPED" ]; then
+        #  echo '<skipped />' >> test-dlt.xml
+        #fi
+        #echo '</testcase></testsuite></testsuites>' >> test-dlt.xml
+        #if [ "$DLT_STATUS" != "SUCCESS" ]; then
+        #  exit 1
+        #fi         
     - name: Publish Test Report
       uses: mikepenz/action-junit-report@v3
       if: success() || failure() # always run even if the previous step fails
