tst integration

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -13,6 +13,7 @@ env:
   DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
   REPO_DIRECTORY: ${{ vars.REPO_DIRECTORY }}
   CLUSTER_ID: ${{ vars.CLUSTER_ID }}
+  TEST_DLT_PIPELINE_ID: 752345209143482
 
 permissions:
   checks: write
@@ -49,15 +50,44 @@ jobs:
         
     - name: Run Tests
       run: |
-        nutter run "$REPO_DIRECTORY/tests/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500
-    
+        nutter run "$REPO_DIRECTORY/tests/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500    
+
+    - name: Run Integration test Pipeline
+      run: |
+        DLT_START=$SECONDS
+        DLT_START_ISO=$(date --iso-8601=seconds)
+        poetry run databricks pipelines start --pipeline-id $(TEST_DLT_PIPELINE_ID) --full-refresh
+        sleep 15
+        while true; do
+          DLT_STATUS=$(poetry run databricks pipelines get --pipeline-id $(TEST_DLT_PIPELINE_ID) |jq -r '.latest_updates[0].state')
+          if [ "$DLT_STATUS" = "COMPLETED" -o "$DLT_STATUS" = "CANCELED" -o "$DLT_STATUS" = "FAILED" ]; then
+            echo "Exiting loop with status '$DLT_STATUS'"
+            break
+          fi
+          echo "DLT pipeline status is '$DLT_STATUS'. Waiting..."
+          sleep 15
+        done
+        DLT_FINISH=$SECONDS
+        DLT_ERRORS=$(( "$DLT_STATUS" = "FAILED" ? 1 : 0 ))
+        DLT_SKIPPED=$(( "$DLT_STATUS" = "CANCELED" ? 1 : 0 ))
+        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites><testsuite name=\"DLT Integration test\" tests=\"1\" skipped=\"$DLT_SKIPPED\" errors=\"$DLT_ERRORS\" failures=\"$DLT_ERRORS\" time=\"$((DLT_FINISH-DLT_START))\" timestamp=\"${DLT_START_ISO}\">" > test-dlt.xml
+        echo "<testcase classname=\"DLTIntegration\" name=\"${TEST_DLT_PIPELINE_NAME}\" time=\"$((DLT_FINISH-DLT_START))\">" >> test-dlt.xml
+        if [ "$DLT_STATUS" = "FAILED" ]; then
+          DLT_UPDATE_ID=$(poetry run databricks pipelines get --pipeline-id $(TEST_DLT_PIPELINE_ID) |jq -r '.latest_updates[0].update_id')
+          echo "<failure message=\"DLT test failure\">Pipeline update with ID ${DLT_UPDATE_ID} has failed</failure>" >> test-dlt.xml
+        elif [ "$DLT_STATUS" = "CANCELED" ]; then
+          echo '<skipped />' >> test-dlt.xml
+        fi
+        echo '</testcase></testsuite></testsuites>' >> test-dlt.xml
+        if [ "$DLT_STATUS" != "COMPLETED" ]; then
+          exit 1
+        fi         
     - name: Publish Test Report
       uses: mikepenz/action-junit-report@v3
       if: success() || failure() # always run even if the previous step fails
       with:
-        report_paths: '**/test-*.xml'    
+        report_paths: '**/test-*.xml'
         
-   
   OnRelease:
     if: startsWith(github.ref_name, 'releases')
     environment: staging
@@ -88,7 +118,7 @@ jobs:
       uses: mikepenz/action-junit-report@v3
       if: success() || failure() # always run even if the previous step fails
       with:
-        report_paths: '**/test-*.xml'
+        report_paths: '**/test-*.xml'  
         
   DeployProduction:
     environment: prod
